sudo: required

language: csharp

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo apt-get install python-dev
  - pip install docker-cloud

script:
  - docker-compose build

after_success:
  - export APP=docker-dotnetcore-starter-kit
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=neocase/$APP
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO:$COMMIT $REPO
  - docker push $REPO
  - docker-cloud stack create -f docker-cloud.yml -n $APP
  - docker-cloud stack redeploy $APP

  

