version: '2'

services:
  docker-dotnetcore-starter-kit:
    image: docker-dotnetcore-starter-kit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - neo_dev
    restart: always
    pid: "host"

networks:
    neo_dev:
      driver: bridge
