version: '2'

services:
  docker-dotnetcore-starter-kit:
    image: docker-dotnetcore-starter-kit:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
